/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;

/**
 *
 * @author Martinez
 */
public class PantallaRetiroSinCuentaCliente extends javax.swing.JFrame {
    private String idClienteEnSesion;
    /**
     * Creates new form PantallaRetiroSinCuenta
     */
    public PantallaRetiroSinCuentaCliente(String cliente) {
        initComponents();
        this.idClienteEnSesion = cliente;
        // Definir un color de fondo (gris azulado oscuro)
        Color grisAzuladoOscuro = new Color(30, 36, 44); // Valores RGB
        // Cambiar el color de fondo del formulario
        getContentPane().setBackground(grisAzuladoOscuro);
        
        
        // Agregar un FocusListener al campo txtNumCuenta
        txtNumCuenta.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando se gana el foco, si el texto es igual a "Numero de Cuenta", borrarlo
                if (txtNumCuenta.getText().equals("Numero de Cuenta")) {
                    txtNumCuenta.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando se pierde el foco, si el texto está vacío, restaurar "Numero de Cuenta"
                if (txtNumCuenta.getText().isEmpty()) {
                    txtNumCuenta.setText("Numero de Cuenta");
                }
            }
        });
        
        // Agregar un FocusListener al campo txtMonto
        txtMonto.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Cuando se gana el foco, si el texto es igual a "Monto", borrarlo
                if (txtMonto.getText().equals("Monto")) {
                    txtMonto.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Cuando se pierde el foco, si el texto está vacío, restaurar "Monto"
                if (txtMonto.getText().isEmpty()) {
                    txtMonto.setText("Monto");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumCuenta = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        btnGenerarFolio = new javax.swing.JButton();
        lblGenerarRetiroSinCuenta = new javax.swing.JLabel();
        btnVolver4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNumCuenta.setText("Numero de Cuenta");

        txtMonto.setText("Monto");

        btnGenerarFolio.setText("Generar Folio");
        btnGenerarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFolioActionPerformed(evt);
            }
        });

        lblGenerarRetiroSinCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGenerarRetiroSinCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerarRetiroSinCuenta.setText("Generar Retiro sin Cuenta");

        btnVolver4.setText("Volver");
        btnVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblGenerarRetiroSinCuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerarFolio))
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblGenerarRetiroSinCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarFolio)
                    .addComponent(btnVolver4))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String generarFolioUnico() {
    // implementa la lógica para generar un folio único
    return java.util.UUID.randomUUID().toString();
    }
    
    private String generarContraseñaAleatoria() {
    // Generar una contraseña aleatoria de 8 dígitos
    Random random = new Random();
    int contraseñaNum = random.nextInt(90000000) + 10000000; // Números entre 10000000 y 99999999
    return String.valueOf(contraseñaNum);
    }
    
    private void guardarFolioYContraseña(String numCuenta, double monto, String folioOperacion, String contraseñaRetiro) {
    // Conectarse a la base de datos y guardar el folio, la contraseña, el número de cuenta y el monto
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banco", "root", "41502Mar");
        String query = "INSERT INTO transaccion (numCuenta, monto, folioOperacion, contraseñaRetiro) VALUES (?, ?, ?, ?)";
        PreparedStatement statement = conn.prepareStatement(query);
        statement.setString(1, numCuenta);
        statement.setDouble(2, monto);
        statement.setString(3, folioOperacion);
        statement.setString(4, contraseñaRetiro);
        statement.executeUpdate();
        conn.close();
        // Notificar al usuario que el folio y la contraseña han sido generados y guardados
        javax.swing.JOptionPane.showMessageDialog(this, "Folio y contraseña generados:\nFolio: " + folioOperacion + "\nContraseña: " + contraseñaRetiro);
    } catch (SQLException e) {
        e.printStackTrace();
        // Manejar la excepción apropiadamente
    }
    }
    
    private void btnGenerarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFolioActionPerformed
        // Obtener el número de cuenta y la cantidad de saldo ingresados por el usuario
    String numCuenta = txtNumCuenta.getText();
    String montoString = txtMonto.getText();
    
    // Validar la entrada del usuario
    if (numCuenta.equals("Número de Cuenta") || montoString.equals("Monto a Retirar")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de cuenta y un monto válido.");
        return;
    }
    
    // Verificar que el monto sea un valor numérico
    double monto;
    try {
        monto = Double.parseDouble(montoString);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto válido.");
        return;
    }
    
    // Verificar que el monto sea positivo
    if (monto <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "El monto a retirar debe ser mayor que cero.");
        return;
    }
    
    // Generar un folio único y una contraseña aleatoria
    String folioOperacion = generarFolioUnico();
    String contraseñaRetiro = generarContraseñaAleatoria();
    
    // Guardar el folio y la contraseña en la base de datos
    guardarFolioYContraseña(numCuenta, monto, folioOperacion, contraseñaRetiro);
    }//GEN-LAST:event_btnGenerarFolioActionPerformed

    private void btnVolver4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver4ActionPerformed
        // TODO add your handling code here:
        PantallaMenuPrincipal menuPrincipal = new PantallaMenuPrincipal(idClienteEnSesion);
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarFolio;
    private javax.swing.JButton btnVolver4;
    private javax.swing.JLabel lblGenerarRetiroSinCuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNumCuenta;
    // End of variables declaration//GEN-END:variables
}
